[tool.pytest.ini_options]
pythonpath = [
    ".",
    "functions"
]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
addopts = "-v --cov=functions/app --cov-report=term-missing" 